"""HTTP API routes."""

from __future__ import annotations

import re
from datetime import date, datetime, timedelta
import logging
from urllib.parse import unquote, urlparse

from fastapi import APIRouter, Depends, HTTPException, Response, status
from sqlalchemy import delete, desc, func, select
from sqlalchemy.orm import Session

from app.config import get_settings
from app.db import get_db
from app.models import (
    Alert,
    BatterStatcastSummary,
    Market,
    MlbDailyCard,
    MlbEdge,
    MlbGame,
    MlbGameEnvironmentSnapshot,
    MlbOddsSnapshot,
    MlbPitcherPropSnapshot,
    PitcherStatcastSummary,
    PitcherPropOddsSnapshot,
    Position,
    Signal,
    Trade,
    Trader,
)
from app.providers.falcon import FalconProvider, get_falcon_health
from app.services.ingestion_health import get_ingestion_health
from app.services.odds_cache import get_odds_cache_health
from app.providers.mlb_stats_api import MlbStatsApiError, MlbStatsApiProvider
from app.providers.odds_api import OddsApiError, OddsApiProvider
from app.providers.pybaseball_provider import PyBaseballError, PyBaseballProvider
from app.providers.weather_api import WeatherApiError, WeatherApiProvider
from app.schemas import (
    AlertOut,
    DashboardSummary,
    MarketOut,
    ScanResult,
    SignalOut,
    TraderCreate,
    TraderOut,
    WatchlistHealth,
)
from app.services.scanner import run_scan_once
from app.services.alerts import DISCORD_TIERS, evaluate_alert_decision
from app.services.mlb_edge_engine import (
    discord_ready_summary,
    edge_to_dict,
    edges_for_date,
    latest_daily_card,
    run_daily_mlb_edges,
)
from app.services.mlb_market_validation import validation_report
from app.services.odds_cache import MLB_PITCHER_PROPS_TTL, MLB_TOTALS_TTL
from app.services.mlb_performance import (
    clv_report,
    grade_edge,
    performance_by_market,
    performance_by_score_band,
    performance_summary,
    top_factors_by_performance,
    update_closing_line_fields,
)

router = APIRouter()
logger = logging.getLogger(__name__)

_SLUG_DATE_RE = re.compile(r"(20\d{2})-(\d{2})-(\d{2})")
_LIVE_PYBASEBALL_DISABLED_MESSAGE = (
    "Live pybaseball requests disabled. Use cached Statcast summaries generated by worker."
)


# ---------------------------- health ----------------------------------------


@router.get("/health")
def health() -> dict[str, object]:
    s = get_settings()
    falcon_health = get_falcon_health()
    ingest = get_ingestion_health()
    odds_cache_health = get_odds_cache_health()
    # "Configured" means a key is set. "Healthy" means calls are actually
    # succeeding — these can disagree (wrong base URL, expired key, etc.).
    return {
        "status": "ok",
        "app": s.app_name,
        "environment": s.environment,
        "default_copy_mode": s.default_copy_mode,
        "auto_trading_enabled": s.enable_auto_trading,
        "database": {"backend": _database_backend(s.database_url)},
        "ingestion": {
            "ingestion_failures": ingest.ingestion_failures,
            "db_rollbacks": ingest.db_rollbacks,
            "last_ingestion_error": ingest.last_ingestion_error,
            "last_ingestion_error_at": (
                ingest.last_ingestion_error_at.isoformat()
                if ingest.last_ingestion_error_at
                else None
            ),
            "last_rollback_at": (
                ingest.last_rollback_at.isoformat() if ingest.last_rollback_at else None
            ),
            "trades_inserted": ingest.trades_inserted,
            "trades_skipped_oversized": ingest.trades_skipped_oversized,
        },
        "providers": {
            "falcon": {
                "configured": s.has_falcon_credentials(),
                "healthy": falcon_health.healthy,
                "calls": falcon_health.calls,
                "successes": falcon_health.successes,
                "success_rate": round(falcon_health.success_rate, 3),
                "last_status_code": falcon_health.last_status_code,
                "last_error": falcon_health.last_error,
                "last_endpoint": falcon_health.last_endpoint,
                "last_scan_at": (
                    falcon_health.last_scan_at.isoformat()
                    if falcon_health.last_scan_at
                    else None
                ),
                "last_scan_calls": falcon_health.last_scan_calls,
                "last_scan_successes": falcon_health.last_scan_successes,
                "base_url": falcon_health.base_url or s.falcon_base_url,
            },
            "polymarket": {"configured": s.has_polymarket_credentials()},
            "kalshi": {"configured": s.has_kalshi_credentials()},
            "odds_api": {
                "configured": s.has_odds_api_credentials(),
                "base_url": s.odds_api_base_url,
                "bookmakers": [b.strip() for b in s.odds_bookmakers.split(",") if b.strip()],
                "cache": {
                    "live_api_calls": odds_cache_health.live_api_calls,
                    "cache_hits": odds_cache_health.cache_hits,
                    "cache_misses": odds_cache_health.cache_misses,
                    "avoided_api_calls": odds_cache_health.avoided_api_calls,
                    "stale_fallbacks": odds_cache_health.stale_fallbacks,
                    "rate_limited_count": odds_cache_health.rate_limited_count,
                    "last_rate_limited_at": (
                        odds_cache_health.last_rate_limited_at.isoformat()
                        if odds_cache_health.last_rate_limited_at else None
                    ),
                    "last_refresh_at": (
                        odds_cache_health.last_refresh_at.isoformat()
                        if odds_cache_health.last_refresh_at else None
                    ),
                    "last_refresh_event_count": odds_cache_health.last_refresh_event_count,
                },
            },
            "mlb_stats_api": {
                "configured": s.mlb_stats_enabled,
                "requires_api_key": False,
            },
            "weather_api": {
                "configured": s.has_weather_api_credentials(),
                "base_url": s.weather_api_base_url,
            },
            "pybaseball": {
                "configured": s.pybaseball_enabled,
                "requires_api_key": False,
                "allow_live_requests": s.allow_live_pybaseball_requests,
            },
        },
        "alerts": {
            "console": {"configured": True},
            "discord": {"configured": bool(s.discord_webhook_url)},
            "telegram": {
                "configured": bool(s.telegram_bot_token and s.telegram_chat_id),
                "has_bot_token": bool(s.telegram_bot_token),
                "has_chat_id": bool(s.telegram_chat_id),
            },
            "email": {
                "configured": bool(
                    s.alert_email_to
                    and s.smtp_host
                    and (s.alert_email_from or s.smtp_username)
                ),
                "has_recipient": bool(s.alert_email_to),
                "has_smtp_host": bool(s.smtp_host),
                "has_from_address": bool(s.alert_email_from or s.smtp_username),
            },
        },
        "timestamp": datetime.utcnow().isoformat(),
    }


def _database_backend(database_url: str) -> str:
    scheme = database_url.split(":", 1)[0].lower() if database_url else ""
    if scheme.startswith("sqlite"):
        return "sqlite"
    if scheme.startswith("postgres") or scheme.startswith("postgresql"):
        return "postgres"
    return "unknown"


# ---------------------------- traders ---------------------------------------


@router.get("/traders", response_model=list[TraderOut])
def list_traders(db: Session = Depends(get_db)) -> list[Trader]:
    return list(db.scalars(select(Trader).order_by(Trader.trust_score.desc())))


@router.post("/traders", response_model=TraderOut, status_code=status.HTTP_201_CREATED)
def create_trader(payload: TraderCreate, db: Session = Depends(get_db)) -> Trader:
    existing = db.scalar(select(Trader).where(Trader.nickname == payload.nickname))
    if existing:
        raise HTTPException(status_code=409, detail=f"trader '{payload.nickname}' already exists")

    if payload.wallet_address:
        existing_wallet = db.scalar(
            select(Trader).where(Trader.wallet_address == payload.wallet_address)
        )
        if existing_wallet:
            raise HTTPException(
                status_code=409,
                detail=f"wallet '{payload.wallet_address}' already exists",
            )

    trader = Trader(**payload.model_dump())
    # MVP guard: never allow live copy_mode through the API.
    if trader.copy_mode == "live" and not get_settings().enable_auto_trading:
        trader.copy_mode = "alert_only"

    db.add(trader)
    db.commit()
    db.refresh(trader)
    return trader


@router.delete(
    "/traders/{trader_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    response_model=None,
    response_class=Response,
)
def delete_trader(trader_id: int, db: Session = Depends(get_db)) -> None:
    trader = db.get(Trader, trader_id)
    if trader is None:
        raise HTTPException(status_code=404, detail=f"trader {trader_id} not found")

    signal_ids = list(
        db.scalars(select(Signal.id).where(Signal.trader_id == trader_id))
    )
    if signal_ids:
        db.execute(delete(Alert).where(Alert.signal_id.in_(signal_ids)))
        db.execute(delete(Signal).where(Signal.id.in_(signal_ids)))

    db.execute(delete(Position).where(Position.trader_id == trader_id))
    db.execute(delete(Trade).where(Trade.trader_id == trader_id))
    db.delete(trader)
    db.commit()
    return None


# ---------------------------- markets ---------------------------------------


@router.get("/markets", response_model=list[MarketOut])
def list_markets(db: Session = Depends(get_db), limit: int = 50) -> list[Market]:
    return list(
        db.scalars(
            select(Market).where(Market.is_active.is_(True)).limit(limit)
        )
    )


# ---------------------------- signals ---------------------------------------


def _enrich_signal(signal: Signal) -> SignalOut:
    base = SignalOut.model_validate(signal)
    if signal.trader:
        base.wallet = signal.trader.wallet_address
        base.trader_nickname = signal.trader.nickname
        if signal.trader.wallet_address:
            base.trader_url = f"https://polymarketanalytics.com/traders/{signal.trader.wallet_address}"
    if signal.market:
        base.market_title = signal.market.title
        base.market_slug = signal.market.slug
        base.market_platform = signal.market.platform
        base.market_created_at = signal.market.created_at
        base.market_updated_at = signal.market.updated_at
        base.market_end_date = signal.market.end_date
        if signal.market.slug:
            if signal.market.platform and signal.market.platform.lower() == "kalshi":
                base.market_url = f"https://kalshi.com/markets/{signal.market.slug.upper()}"
            else:
                base.market_url = f"https://polymarket.com/event/{signal.market.slug}"
    return base


@router.get("/signals", response_model=list[SignalOut])
def list_signals(db: Session = Depends(get_db), limit: int = 50) -> list[SignalOut]:
    signals = list(
        db.scalars(select(Signal).order_by(desc(Signal.created_at)).limit(limit))
    )
    return [_enrich_signal(s) for s in signals]


# ---------------------------- alerts ----------------------------------------


@router.get("/alerts", response_model=list[AlertOut])
def list_alerts(db: Session = Depends(get_db), limit: int = 50) -> list[Alert]:
    return list(db.scalars(select(Alert).order_by(desc(Alert.created_at)).limit(limit)))


# ---------------------------- sportsbook odds -------------------------------


def _odds_provider() -> OddsApiProvider:
    s = get_settings()
    return OddsApiProvider(s.odds_api_key, s.odds_api_base_url, s.odds_bookmakers)


def _odds_error(exc: Exception) -> HTTPException:
    if isinstance(exc, OddsApiError):
        return HTTPException(status_code=400, detail=str(exc))
    if hasattr(exc, "response"):
        response = exc.response  # type: ignore[attr-defined]
        return HTTPException(
            status_code=response.status_code,
            detail=response.text[:500],
        )
    return HTTPException(status_code=502, detail=f"{type(exc).__name__}: {exc}")


@router.get("/odds/sports")
async def odds_sports() -> list[dict[str, object]]:
    try:
        return await _odds_provider().sports()
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/bookmakers")
async def odds_bookmakers() -> list[dict[str, object]]:
    try:
        return await _odds_provider().bookmakers()
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/bookmakers/selected")
async def odds_selected_bookmakers() -> object:
    try:
        return await _odds_provider().selected_bookmakers()
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/leagues")
async def odds_leagues(sport: str) -> list[dict[str, object]]:
    try:
        return await _odds_provider().leagues(sport)
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/events")
async def odds_events(
    sport: str,
    league: str | None = None,
    status: str | None = "pending,live",
    bookmaker: str | None = None,
    date_from: str | None = None,
    date_to: str | None = None,
) -> list[dict[str, object]]:
    try:
        return await _odds_provider().events(
            sport,
            league=league,
            status=status,
            bookmaker=bookmaker,
            date_from=date_from,
            date_to=date_to,
        )
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/events/live")
async def odds_live_events(sport: str | None = None) -> list[dict[str, object]]:
    try:
        return await _odds_provider().live_events(sport)
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/events/search")
async def odds_search_events(query: str) -> list[dict[str, object]]:
    if len(query.strip()) < 3:
        raise HTTPException(status_code=400, detail="query must be at least 3 characters")
    try:
        return await _odds_provider().search_events(query)
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/events/{event_id}")
async def odds_event(event_id: str) -> dict[str, object]:
    try:
        return await _odds_provider().event(event_id)
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/compare")
async def odds_compare(
    event_id: str,
    bookmakers: str | None = None,
    market: str | None = None,
    side: str | None = None,
    line: float | None = None,
) -> dict[str, object]:
    """Compare sportsbook lines across books for one event."""
    try:
        return await _odds_provider().compare_lines(
            event_id,
            bookmakers=bookmakers,
            market=market,
            side=side,
            line=line,
        )
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


@router.get("/odds/movements")
async def odds_movements(
    event_id: str,
    bookmaker: str,
    market: str,
    market_line: float | None = None,
) -> dict[str, object]:
    try:
        return await _odds_provider().odds_movements(event_id, bookmaker, market, market_line)
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc


# ---------------------------- MLB StatsAPI ----------------------------------


def _mlb_provider() -> MlbStatsApiProvider:
    if not get_settings().mlb_stats_enabled:
        raise HTTPException(status_code=503, detail="MLB StatsAPI integration is disabled")
    return MlbStatsApiProvider()


def _mlb_error(exc: Exception) -> HTTPException:
    if isinstance(exc, HTTPException):
        return exc
    if isinstance(exc, MlbStatsApiError):
        return HTTPException(status_code=400, detail=str(exc))
    return HTTPException(status_code=502, detail=f"{type(exc).__name__}: {exc}")


@router.get("/mlb/schedule")
async def mlb_schedule(
    game_date: str | None = None,
    start_date: str | None = None,
    end_date: str | None = None,
    team_id: int | None = None,
    season: int | None = None,
) -> dict[str, object]:
    """Return MLB schedule data, including probable pitchers when available."""
    try:
        return await _mlb_provider().schedule(
            game_date=game_date,
            start_date=start_date,
            end_date=end_date,
            team_id=team_id,
            season=season,
        )
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/games/live")
async def mlb_live_scores(game_date: str | None = None) -> dict[str, object]:
    """Return compact MLB game status and live score summaries."""
    try:
        return await _mlb_provider().live_scores(game_date=game_date)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/games/{game_pk}")
async def mlb_game(game_pk: int) -> dict[str, object]:
    try:
        return await _mlb_provider().game(game_pk)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/games/{game_pk}/linescore")
async def mlb_linescore(game_pk: int) -> dict[str, object]:
    try:
        return await _mlb_provider().linescore(game_pk)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/games/{game_pk}/boxscore")
async def mlb_boxscore(game_pk: int) -> dict[str, object]:
    try:
        return await _mlb_provider().boxscore(game_pk)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/games/{game_pk}/lineups")
async def mlb_lineups(game_pk: int) -> dict[str, object]:
    try:
        return await _mlb_provider().lineups(game_pk)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/probable-pitchers")
async def mlb_probable_pitchers(game_date: str | None = None) -> dict[str, object]:
    try:
        return await _mlb_provider().probable_pitchers(game_date=game_date)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/teams")
async def mlb_teams(season: int | None = None) -> dict[str, object]:
    try:
        return await _mlb_provider().teams(season=season)
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/teams/{team_id}/stats")
async def mlb_team_stats(
    team_id: int,
    season: int,
    group: str = "hitting",
    stats: str = "season",
    game_type: str = "R",
) -> dict[str, object]:
    try:
        return await _mlb_provider().team_stats(
            team_id,
            season=season,
            group=group,
            stats=stats,
            game_type=game_type,
        )
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/players/{person_id}/stats")
async def mlb_player_stats(
    person_id: int,
    season: int,
    group: str = "hitting",
    stats: str = "season",
    game_type: str = "R",
) -> dict[str, object]:
    try:
        return await _mlb_provider().player_stats(
            person_id,
            season=season,
            group=group,
            stats=stats,
            game_type=game_type,
        )
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


@router.get("/mlb/history")
async def mlb_history(
    start_date: str,
    end_date: str,
    team_id: int | None = None,
) -> dict[str, object]:
    try:
        return await _mlb_provider().historical_games(
            start_date=start_date,
            end_date=end_date,
            team_id=team_id,
        )
    except Exception as exc:  # noqa: BLE001
        raise _mlb_error(exc) from exc


# ---------------------------- weather ---------------------------------------


def _weather_provider() -> WeatherApiProvider:
    s = get_settings()
    return WeatherApiProvider(s.weather_api_key, s.weather_api_base_url)


def _weather_error(exc: Exception) -> HTTPException:
    if isinstance(exc, WeatherApiError):
        return HTTPException(status_code=400, detail=str(exc))
    if hasattr(exc, "response"):
        response = exc.response  # type: ignore[attr-defined]
        return HTTPException(status_code=response.status_code, detail=response.text[:500])
    return HTTPException(status_code=502, detail=f"{type(exc).__name__}: {exc}")


@router.get("/weather/current")
async def weather_current(q: str) -> dict[str, object]:
    try:
        return await _weather_provider().current(q)
    except Exception as exc:  # noqa: BLE001
        raise _weather_error(exc) from exc


@router.get("/weather/forecast")
async def weather_forecast(
    q: str,
    days: int = 1,
    dt: str | None = None,
    hour: int | None = None,
) -> dict[str, object]:
    try:
        return await _weather_provider().forecast(q, days=days, dt=dt, hour=hour)
    except Exception as exc:  # noqa: BLE001
        raise _weather_error(exc) from exc


@router.get("/weather/history")
async def weather_history(
    q: str,
    dt: str,
    hour: int | None = None,
    end_dt: str | None = None,
) -> dict[str, object]:
    try:
        return await _weather_provider().history(q, dt=dt, hour=hour, end_dt=end_dt)
    except Exception as exc:  # noqa: BLE001
        raise _weather_error(exc) from exc


@router.get("/weather/baseball")
async def weather_baseball(
    q: str,
    game_date: str | None = None,
    hour: int | None = None,
) -> dict[str, object]:
    """Return compact weather fields that matter for baseball run totals."""
    try:
        return await _weather_provider().baseball_weather(q, game_date=game_date, hour=hour)
    except Exception as exc:  # noqa: BLE001
        raise _weather_error(exc) from exc


# ---------------------------- pybaseball ------------------------------------


def _pybaseball_provider() -> PyBaseballProvider:
    if not get_settings().pybaseball_enabled:
        raise HTTPException(status_code=503, detail="pybaseball integration is disabled")
    return PyBaseballProvider()


def _pybaseball_error(exc: Exception) -> HTTPException:
    if isinstance(exc, HTTPException):
        return exc
    if isinstance(exc, PyBaseballError):
        return HTTPException(status_code=400, detail=str(exc))
    return HTTPException(status_code=502, detail=f"{type(exc).__name__}: {exc}")


def _require_live_pybaseball() -> None:
    s = get_settings()
    if not s.allow_live_pybaseball_requests:
        logger.warning("Blocked live pybaseball request; use Statcast cache worker instead")
        raise HTTPException(status_code=409, detail=_LIVE_PYBASEBALL_DISABLED_MESSAGE)


def _validate_live_statcast_window(start_dt: str, end_dt: str | None, limit: int) -> None:
    _require_live_pybaseball()
    s = get_settings()
    if limit > s.max_live_statcast_rows:
        raise HTTPException(
            status_code=400,
            detail=f"limit must be <= {s.max_live_statcast_rows} for live Statcast requests",
        )
    try:
        start = date.fromisoformat(start_dt)
        end = date.fromisoformat(end_dt or start_dt)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail="dates must use YYYY-MM-DD format") from exc
    if end < start:
        raise HTTPException(status_code=400, detail="end_dt must be on or after start_dt")
    days = (end - start).days + 1
    if days > s.max_live_statcast_days:
        logger.warning("Rejected live Statcast range over %s days: %s to %s", s.max_live_statcast_days, start_dt, end_dt)
        raise HTTPException(
            status_code=400,
            detail=f"live Statcast ranges are limited to {s.max_live_statcast_days} days",
        )


def _summary_payload(summary: PitcherStatcastSummary | BatterStatcastSummary) -> dict[str, object]:
    return {
        "player_id": summary.player_id,
        "player_name": summary.player_name,
        "season": summary.season,
        "last_n_days": summary.last_n_days,
        "games": summary.games,
        "innings_pitched": summary.innings_pitched,
        "strikeouts": summary.strikeouts,
        "walks": summary.walks,
        "pitch_count_avg": summary.pitch_count_avg,
        "strikeouts_per_start": summary.strikeouts_per_start,
        "whiff_rate": summary.whiff_rate,
        "chase_rate": summary.chase_rate,
        "k_rate": summary.k_rate,
        "updated_at": summary.updated_at.isoformat() if summary.updated_at else None,
        "source": summary.source,
    }


@router.get("/baseball/player-lookup")
async def baseball_player_lookup(first: str, last: str) -> list[dict[str, object]]:
    _require_live_pybaseball()
    try:
        return await _pybaseball_provider().player_lookup(first, last)
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/statcast")
async def baseball_statcast(
    start_dt: str,
    end_dt: str | None = None,
    limit: int = 500,
) -> list[dict[str, object]]:
    _validate_live_statcast_window(start_dt, end_dt, limit)
    try:
        return await _pybaseball_provider().statcast(start_dt, end_dt, limit=limit)
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/pitchers/{pitcher_id}/statcast")
async def baseball_pitcher_statcast(
    pitcher_id: int,
    start_dt: str,
    end_dt: str | None = None,
    limit: int = 500,
) -> list[dict[str, object]]:
    _validate_live_statcast_window(start_dt, end_dt, limit)
    try:
        return await _pybaseball_provider().pitcher_statcast(
            pitcher_id,
            start_dt,
            end_dt,
            limit=limit,
        )
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/batters/{batter_id}/statcast")
async def baseball_batter_statcast(
    batter_id: int,
    start_dt: str,
    end_dt: str | None = None,
    limit: int = 500,
) -> list[dict[str, object]]:
    _validate_live_statcast_window(start_dt, end_dt, limit)
    try:
        return await _pybaseball_provider().batter_statcast(
            batter_id,
            start_dt,
            end_dt,
            limit=limit,
        )
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/pitching-stats")
async def baseball_pitching_stats(
    start_season: int,
    end_season: int | None = None,
) -> list[dict[str, object]]:
    _require_live_pybaseball()
    try:
        return await _pybaseball_provider().pitching_stats(start_season, end_season)
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/batting-stats")
async def baseball_batting_stats(
    start_season: int,
    end_season: int | None = None,
) -> list[dict[str, object]]:
    _require_live_pybaseball()
    try:
        return await _pybaseball_provider().batting_stats(start_season, end_season)
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/players/{player_id}/splits")
async def baseball_player_splits(
    player_id: str,
    season: int | None = None,
    pitching_splits: bool = False,
    limit: int = 500,
) -> list[dict[str, object]]:
    _require_live_pybaseball()
    try:
        return await _pybaseball_provider().player_splits(
            player_id,
            season=season,
            pitching_splits=pitching_splits,
            limit=limit,
        )
    except Exception as exc:  # noqa: BLE001
        raise _pybaseball_error(exc) from exc


@router.get("/baseball/pitchers/{pitcher_id}/statcast-summary")
def baseball_pitcher_statcast_summary(
    pitcher_id: int,
    season: int | None = None,
    last_n_days: int | None = None,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    query = select(PitcherStatcastSummary).where(PitcherStatcastSummary.player_id == pitcher_id)
    if season is not None:
        query = query.where(PitcherStatcastSummary.season == season)
    if last_n_days is not None:
        query = query.where(PitcherStatcastSummary.last_n_days == last_n_days)
    summary = db.scalar(query.order_by(desc(PitcherStatcastSummary.updated_at)).limit(1))
    if summary is None:
        raise HTTPException(
            status_code=404,
            detail="No cached pitcher Statcast summary found. Run python -m scripts.update_statcast_cache.",
        )
    return _summary_payload(summary)


@router.get("/baseball/batters/{batter_id}/statcast-summary")
def baseball_batter_statcast_summary(
    batter_id: int,
    season: int | None = None,
    last_n_days: int | None = None,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    query = select(BatterStatcastSummary).where(BatterStatcastSummary.player_id == batter_id)
    if season is not None:
        query = query.where(BatterStatcastSummary.season == season)
    if last_n_days is not None:
        query = query.where(BatterStatcastSummary.last_n_days == last_n_days)
    summary = db.scalar(query.order_by(desc(BatterStatcastSummary.updated_at)).limit(1))
    if summary is None:
        raise HTTPException(
            status_code=404,
            detail="No cached batter Statcast summary found. Run python -m scripts.update_statcast_cache.",
        )
    return _summary_payload(summary)


@router.get("/baseball/statcast-cache/status")
def baseball_statcast_cache_status(db: Session = Depends(get_db)) -> dict[str, object]:
    pitcher_count = db.scalar(select(func.count(PitcherStatcastSummary.id))) or 0
    batter_count = db.scalar(select(func.count(BatterStatcastSummary.id))) or 0
    latest_pitcher = db.scalar(select(func.max(PitcherStatcastSummary.updated_at)))
    latest_batter = db.scalar(select(func.max(BatterStatcastSummary.updated_at)))
    return {
        "pitcher_summaries": pitcher_count,
        "batter_summaries": batter_count,
        "latest_pitcher_updated_at": latest_pitcher.isoformat() if latest_pitcher else None,
        "latest_batter_updated_at": latest_batter.isoformat() if latest_batter else None,
        "live_pybaseball_requests_allowed": get_settings().allow_live_pybaseball_requests,
    }


# ---------------------------- MLB edge engine --------------------------------


@router.get("/mlb/edges/today")
def mlb_edges_today(
    game_date: str | None = None,
    limit: int = 100,
    db: Session = Depends(get_db),
) -> list[dict[str, object]]:
    target = game_date or get_settings().mlb_edge_default_game_date or date.today().isoformat()
    edges = list(
        db.scalars(
            select(MlbEdge)
            .where(MlbEdge.generated_for_date == target)
            .where(MlbEdge.is_valid.is_(True))
            .order_by(desc(MlbEdge.score))
            .limit(limit)
        )
    )
    return [_edge_payload_with_context(db, edge) for edge in edges]


@router.post("/mlb/edges/run")
async def mlb_edges_run(
    game_date: str | None = None,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    try:
        return await run_daily_mlb_edges(db, game_date=game_date)
    except Exception as exc:  # noqa: BLE001
        db.rollback()
        logger.exception("MLB edge run failed")
        raise HTTPException(status_code=502, detail=f"{type(exc).__name__}: {exc}") from exc


@router.get("/mlb/edges/{edge_id}")
def mlb_edge_detail(edge_id: int, db: Session = Depends(get_db)) -> dict[str, object]:
    edge = db.get(MlbEdge, edge_id)
    if edge is None:
        raise HTTPException(status_code=404, detail=f"MLB edge {edge_id} not found")
    payload = _edge_payload_with_context(db, edge)
    payload["discord_summary"] = (
        discord_ready_summary(edge)
        if edge.is_valid and edge.score >= get_settings().mlb_discord_min_score
        else None
    )
    return payload


@router.get("/mlb/daily-card")
def mlb_daily_card(
    game_date: str | None = None,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    target = game_date or get_settings().mlb_edge_default_game_date
    card = latest_daily_card(db, card_date=target)
    if card is None:
        raise HTTPException(
            status_code=404,
            detail="No MLB daily card found. Run POST /mlb/edges/run first.",
        )
    return card


@router.get("/mlb/games/{game_pk}/edge-summary")
def mlb_game_edge_summary(game_pk: int, db: Session = Depends(get_db)) -> dict[str, object]:
    game = db.scalar(select(MlbGame).where(MlbGame.game_pk == game_pk))
    edges = list(
        db.scalars(
            select(MlbEdge)
            .where(MlbEdge.game_pk == game_pk)
            .where(MlbEdge.is_valid.is_(True))
            .order_by(desc(MlbEdge.score))
        )
    )
    env = db.scalar(
        select(MlbGameEnvironmentSnapshot)
        .where(MlbGameEnvironmentSnapshot.game_pk == game_pk)
        .order_by(desc(MlbGameEnvironmentSnapshot.captured_at))
        .limit(1)
    )
    if game is None and not edges:
        raise HTTPException(status_code=404, detail=f"No MLB edge data for game {game_pk}")
    return {
        "game": _mlb_game_payload(game) if game else None,
        "environment": _mlb_environment_payload(env) if env else None,
        "edges": [_edge_payload_with_context(db, edge) for edge in edges],
    }


@router.get("/mlb/debug/sources")
def mlb_debug_sources(db: Session = Depends(get_db)) -> dict[str, object]:
    settings = get_settings()
    return {
        "providers": {
            "mlb_stats_api": {"configured": settings.mlb_stats_enabled, "requires_api_key": False},
            "weather_api": {"configured": settings.has_weather_api_credentials()},
            "odds_api": {"configured": settings.has_odds_api_credentials()},
            "pybaseball_live": {"allowed": settings.allow_live_pybaseball_requests},
            "statcast_cache": baseball_statcast_cache_status(db),
        },
        "row_counts": {
            "mlb_games": db.scalar(select(func.count(MlbGame.id))) or 0,
            "environment_snapshots": db.scalar(select(func.count(MlbGameEnvironmentSnapshot.id))) or 0,
            "odds_snapshots": db.scalar(select(func.count(MlbOddsSnapshot.id))) or 0,
            "pitcher_prop_snapshots": db.scalar(select(func.count(MlbPitcherPropSnapshot.id))) or 0,
            "pitcher_prop_odds_snapshots": db.scalar(select(func.count(PitcherPropOddsSnapshot.id))) or 0,
            "edges": db.scalar(select(func.count(MlbEdge.id))) or 0,
            "daily_cards": db.scalar(select(func.count(MlbDailyCard.id))) or 0,
        },
    }


@router.get("/mlb/debug/pitcher-props")
def mlb_debug_pitcher_props(
    game_pk: int | None = None,
    player_name: str | None = None,
    limit: int = 100,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    filters = []
    if game_pk is not None:
        filters.append(PitcherPropOddsSnapshot.game_pk == game_pk)
    if player_name:
        pattern = f"%{player_name}%"
        filters.append(PitcherPropOddsSnapshot.player_name.ilike(pattern))
    query = (
        select(PitcherPropOddsSnapshot)
        .where(*filters)
        .order_by(desc(PitcherPropOddsSnapshot.timestamp))
        .limit(limit)
    )
    rows = list(db.scalars(query))
    return {
        "count": len(rows),
        "rows": [
            {
                "game_pk": row.game_pk,
                "sportsbook_event_id": row.sportsbook_event_id,
                "player_name": row.player_name,
                "matched_pitcher_name": row.matched_pitcher_name,
                "line": row.line,
                "over_price": row.over_price,
                "under_price": row.under_price,
                "sportsbook": row.sportsbook,
                "timestamp": row.timestamp.isoformat() if row.timestamp else None,
                "source": row.source,
            }
            for row in rows
        ],
    }


# ---------------------------- MLB odds debug --------------------------------


def _mlb_card_date(game_date: str | None) -> str:
    return game_date or get_settings().mlb_edge_default_game_date or date.today().isoformat()


def _parse_dt(value: Any) -> datetime | None:
    if not value:
        return None
    if isinstance(value, datetime):
        return value
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None


def _latest_odds_snapshot(db: Session, game_pk: int) -> MlbOddsSnapshot | None:
    return db.scalar(
        select(MlbOddsSnapshot)
        .where(MlbOddsSnapshot.game_pk == game_pk)
        .order_by(desc(MlbOddsSnapshot.captured_at))
        .limit(1)
    )


def _latest_prop_snapshot(db: Session, game_pk: int) -> MlbPitcherPropSnapshot | None:
    return db.scalar(
        select(MlbPitcherPropSnapshot)
        .where(MlbPitcherPropSnapshot.game_pk == game_pk)
        .order_by(desc(MlbPitcherPropSnapshot.captured_at))
        .limit(1)
    )


def _best_book_timestamp_from_rows(
    rows: list[dict[str, Any]] | None,
    *,
    book: str | None,
    line: float | None,
    timestamp_key: str,
    book_key: str,
) -> str | None:
    if not rows or not book:
        return None
    candidates: list[datetime] = []
    for row in rows:
        if str(row.get(book_key) or "") != book:
            continue
        if line is not None:
            try:
                row_line = float(row.get("line"))
            except (TypeError, ValueError):
                row_line = None
            if row_line is not None and abs(row_line - line) > 0.0001:
                continue
        ts = _parse_dt(row.get(timestamp_key))
        if ts:
            candidates.append(ts)
    if not candidates:
        return None
    return max(candidates).isoformat()


def _source_url_from_rows(
    rows: list[dict[str, Any]] | None,
    *,
    book: str | None,
    side: str | None,
    line: float | None,
) -> str | None:
    if not rows or not book or not side:
        return None
    side_key = str(side).lower()
    for row in rows:
        if str(row.get("bookmaker") or "") != book:
            continue
        if line is not None:
            try:
                row_line = float(row.get("line"))
            except (TypeError, ValueError):
                row_line = None
            if row_line is not None and abs(row_line - line) > 0.0001:
                continue
        links = row.get("direct_links") or {}
        if isinstance(links, dict):
            link = links.get(side_key)
            if link:
                return str(link)
    return None


def _edge_payload_with_context(db: Session, edge: MlbEdge) -> dict[str, object]:
    payload = edge_to_dict(edge)
    game = db.scalar(select(MlbGame).where(MlbGame.game_pk == edge.game_pk))
    if game:
        payload["game_date"] = game.game_date
        payload["game_start_time"] = game.start_time.isoformat() if game.start_time else None

    now = datetime.utcnow()
    if edge.edge_type == "pitcher_strikeouts":
        snap = _latest_prop_snapshot(db, edge.game_pk)
        if snap:
            payload["odds_snapshot_captured_at"] = snap.captured_at.isoformat() if snap.captured_at else None
            payload["odds_snapshot_source"] = snap.source
            payload["best_book_updated_at"] = _best_book_timestamp_from_rows(
                snap.rows,
                book=edge.best_book,
                line=edge.line,
                timestamp_key="timestamp",
                book_key="sportsbook",
            )
            age_minutes = int((now - snap.captured_at).total_seconds() / 60) if snap.captured_at else None
            payload["odds_data_age_minutes"] = age_minutes
            payload["odds_stale"] = bool(age_minutes is not None and age_minutes > MLB_PITCHER_PROPS_TTL.total_seconds() / 60)
    else:
        snap = _latest_odds_snapshot(db, edge.game_pk)
        if snap:
            payload["odds_snapshot_captured_at"] = snap.captured_at.isoformat() if snap.captured_at else None
            payload["odds_snapshot_source"] = snap.source
            payload["best_book_updated_at"] = _best_book_timestamp_from_rows(
                snap.rows,
                book=edge.best_book,
                line=edge.line,
                timestamp_key="updated_at",
                book_key="bookmaker",
            )
            payload["source_url"] = _source_url_from_rows(
                snap.rows,
                book=edge.best_book,
                side=edge.side,
                line=edge.line,
            )
            age_minutes = int((now - snap.captured_at).total_seconds() / 60) if snap.captured_at else None
            payload["odds_data_age_minutes"] = age_minutes
            payload["odds_stale"] = bool(age_minutes is not None and age_minutes > MLB_TOTALS_TTL.total_seconds() / 60)
    return payload


@router.get("/mlb/debug/odds/events")
async def mlb_debug_odds_events(
    game_date: str | None = None,
    live: bool = False,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    """MLB events for the slate. Cache-first; pass ?live=true to bypass.

    The cache is populated by `refresh_mlb_odds_cache` (run via the edge
    engine or the closing-line script). When ?live=true we still go through
    the same refresh code path so the result is persisted for reuse.
    """
    from app.services import odds_cache
    from app.services.mlb_edge_engine import ODDS_MLB_LEAGUE, ODDS_MLB_SPORT

    card_date = _mlb_card_date(game_date)

    if not live:
        events = odds_cache.get_cached_events_list(db, game_date=card_date)
        if events is not None:
            return {
                "game_date": card_date,
                "sport": ODDS_MLB_SPORT,
                "league": ODDS_MLB_LEAGUE,
                "source": "cache",
                "count": len(events),
                "events": events,
            }

    provider = _odds_provider()
    try:
        # Force=True so even a fresh cache row gets re-fetched on ?live=true.
        refresh = await odds_cache.refresh_mlb_odds_cache(
            db, provider, [], game_date=card_date, force=live,
        )
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc
    events = odds_cache.get_cached_events_list(db, game_date=card_date) or []
    return {
        "game_date": card_date,
        "sport": ODDS_MLB_SPORT,
        "league": ODDS_MLB_LEAGUE,
        "source": "live" if live else "cache (after refresh)",
        "count": len(events),
        "events": events,
        "refresh": refresh.as_dict(),
    }


@router.get("/mlb/debug/odds/event-match")
async def mlb_debug_odds_event_match(
    game_pk: int | None = None,
    game_date: str | None = None,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    """Show, per MLB game, which Odds-API event we matched (or why we didn't).

    Cache-only — does not hit the upstream. Run a refresh first if the cache
    is empty.
    """
    from app.services import odds_cache
    from app.services.mlb_edge_engine import _load_games

    card_date = _mlb_card_date(game_date)
    mlb = _mlb_provider()

    games = await _load_games(mlb, card_date)
    if game_pk is not None:
        games = [g for g in games if int(g.get("game_pk") or 0) == game_pk]
        if not games:
            raise HTTPException(status_code=404, detail=f"No MLB game for pk={game_pk} on {card_date}")

    results, unmatched_events = odds_cache.matches_for_games(
        db, games, game_date=card_date,
    )
    events = odds_cache.get_cached_events_list(db, game_date=card_date) or []
    return {
        "game_date": card_date,
        "mlb_games": len(games),
        "odds_events": len(events),
        "matches": [r.as_dict() for r in results],
        "unmatched_games": [r.as_dict() for r in results if not r.matched_event_id],
        "unmatched_events": [
            {"id": e.get("id"), "home": e.get("home"), "away": e.get("away")}
            for e in unmatched_events
        ],
    }


@router.get("/mlb/debug/odds/raw")
async def mlb_debug_odds_raw(
    event_id: str,
    live: bool = False,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    """Raw `/odds` payload for a single event_id. Cache-first.

    Pass ?live=true to force a single upstream fetch (counted against the
    rate limit). Cache-only calls never hit the API.
    """
    from app.services import odds_cache

    if not live:
        payload = odds_cache.get_cached_event_odds(db, event_id)
        if payload is not None:
            return {"event_id": event_id, "source": "cache", "payload": payload}

    provider = _odds_provider()
    try:
        payload = await provider.odds(event_id)
    except Exception as exc:  # noqa: BLE001
        raise _odds_error(exc) from exc
    # Persist into the cache so subsequent debug calls reuse it.
    odds_cache._upsert_snapshot(  # noqa: SLF001 — debug-only escape hatch
        db,
        sport=odds_cache.ODDS_MLB_SPORT,
        event_id=event_id,
        market_type=odds_cache.MARKET_TYPE_EVENT_ODDS,
        payload=payload,
        ttl=odds_cache.MLB_TOTALS_TTL,
    )
    db.commit()
    return {"event_id": event_id, "source": "live", "payload": payload}


@router.get("/mlb/debug/odds/markets")
async def mlb_debug_odds_markets(
    event_id: str,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    """Inventory the markets for one event_id (cache-only)."""
    from app.services import odds_cache
    from app.services.mlb_odds_analysis import summarize_markets

    payload = odds_cache.get_cached_event_odds(db, event_id)
    if payload is None:
        raise HTTPException(
            status_code=404,
            detail=(
                f"No cached odds for event_id={event_id!r}. Run POST "
                f"/mlb/edges/run or GET /mlb/debug/odds/raw?event_id=...&live=true"
            ),
        )
    return summarize_markets(payload)


@router.get("/mlb/debug/odds-cache")
def mlb_debug_odds_cache(db: Session = Depends(get_db)) -> dict[str, object]:
    """Inventory + metrics for the centralized Odds-API cache.

    Surfaces: row count, fresh vs. stale, by-market-type counts, live API
    calls, cache hits/misses, avoided calls, 429s, and last refresh state.
    """
    from app.services import odds_cache

    return odds_cache.cache_summary(db)


@router.get("/mlb/debug/market-validation")
def mlb_debug_market_validation() -> dict[str, object]:
    """Validation counters + recent rejected markets."""
    return validation_report()


@router.get("/mlb/debug/odds-providers")
def mlb_debug_odds_providers() -> dict[str, object]:
    """Primary/backup odds provider status and fallback telemetry."""
    from app.services import odds_cache

    return odds_cache.get_odds_provider_health()


@router.post("/mlb/debug/odds-cache/refresh")
async def mlb_debug_odds_cache_refresh(
    game_date: str | None = None,
    db: Session = Depends(get_db),
) -> dict[str, object]:
    """Force a refresh of the centralized cache. Operator-triggered."""
    from app.services import odds_cache
    from app.services.mlb_edge_engine import _load_games

    card_date = _mlb_card_date(game_date)
    mlb = _mlb_provider()
    provider = _odds_provider()
    games = await _load_games(mlb, card_date)
    result = await odds_cache.refresh_mlb_odds_cache(
        db, provider, games, game_date=card_date, force=True,
    )
    return result.as_dict()


@router.post("/mlb/debug/closing-lines/run")
async def mlb_debug_run_closing_lines(window_minutes: int = 30) -> dict[str, object]:
    """Run the closing-line updater script once."""
    from scripts.update_mlb_closing_lines import main_async

    exit_code = await main_async(["--window-minutes", str(window_minutes)])
    return {"status": "ok" if exit_code == 0 else "error", "exit_code": exit_code}


@router.post("/mlb/debug/grade-results/run")
async def mlb_debug_run_grade_results() -> dict[str, object]:
    """Run the MLB grading script once."""
    from scripts.grade_mlb_results import main_async

    exit_code = await main_async([])
    return {"status": "ok" if exit_code == 0 else "error", "exit_code": exit_code}


@router.post("/mlb/edges/{edge_id}/grade")
def mlb_grade_edge(
    edge_id: int,
    payload: dict[str, object],
    db: Session = Depends(get_db),
) -> dict[str, object]:
    edge = db.get(MlbEdge, edge_id)
    if edge is None:
        raise HTTPException(status_code=404, detail=f"MLB edge {edge_id} not found")
    outcome = str(payload.get("win_loss_push") or "").lower()
    if outcome and outcome not in {"win", "loss", "push"}:
        raise HTTPException(status_code=400, detail="win_loss_push must be win, loss, or push")
    grade_edge(
        edge,
        result=str(payload.get("result")) if payload.get("result") is not None else None,
        win_loss_push=outcome or None,
        opening_line=_optional_float(payload.get("opening_line")),
        current_line=_optional_float(payload.get("current_line")),
        closing_line=_optional_float(payload.get("closing_line")),
        closing_price=_optional_float(payload.get("closing_price")),
    )
    db.commit()
    db.refresh(edge)
    return edge_to_dict(edge)


@router.post("/mlb/edges/update-closing-lines")
def mlb_update_closing_lines(
    payload: dict[str, object],
    db: Session = Depends(get_db),
) -> dict[str, object]:
    updates = payload.get("updates")
    if not isinstance(updates, list):
        raise HTTPException(status_code=400, detail="payload must include updates list")
    updated = 0
    missing: list[int] = []
    for row in updates:
        if not isinstance(row, dict):
            continue
        edge_id = row.get("edge_id") or row.get("id")
        if edge_id is None:
            continue
        edge = db.get(MlbEdge, int(edge_id))
        if edge is None:
            missing.append(int(edge_id))
            continue
        update_closing_line_fields(
            edge,
            closing_line=_optional_float(row.get("closing_line")),
            closing_price=_optional_float(row.get("closing_price")),
        )
        updated += 1
    db.commit()
    return {"updated": updated, "missing_edge_ids": missing}


@router.get("/mlb/performance/summary")
def mlb_performance_summary(db: Session = Depends(get_db)) -> dict[str, object]:
    data = performance_summary(db)
    data["top_factors_by_performance"] = top_factors_by_performance(db)[:10]
    return data


@router.get("/mlb/performance/by-market")
def mlb_performance_by_market(db: Session = Depends(get_db)) -> list[dict[str, object]]:
    return performance_by_market(db)


@router.get("/mlb/performance/by-score-band")
def mlb_performance_by_score_band(db: Session = Depends(get_db)) -> list[dict[str, object]]:
    return performance_by_score_band(db)


@router.get("/mlb/performance/clv")
def mlb_performance_clv(db: Session = Depends(get_db)) -> dict[str, object]:
    return clv_report(db)


def _optional_float(value: object) -> float | None:
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=f"Invalid numeric value: {value}") from exc


def _mlb_game_payload(game: MlbGame) -> dict[str, object]:
    return {
        "game_pk": game.game_pk,
        "game_date": game.game_date,
        "home_team": game.home_team,
        "away_team": game.away_team,
        "venue": game.venue,
        "probable_home_pitcher": game.probable_home_pitcher,
        "probable_away_pitcher": game.probable_away_pitcher,
        "game_status": game.game_status,
        "start_time": game.start_time.isoformat() if game.start_time else None,
        "weather_location_query": game.weather_location_query,
    }


def _mlb_environment_payload(env: MlbGameEnvironmentSnapshot) -> dict[str, object]:
    return {
        "temperature_score": env.temperature_score,
        "wind_score": env.wind_score,
        "humidity_score": env.humidity_score,
        "precipitation_risk": env.precipitation_risk,
        "park_factor": env.park_factor,
        "run_environment_score": env.run_environment_score,
        "under_environment_score": env.under_environment_score,
        "k_environment_score": env.k_environment_score,
        "warnings": env.warnings or [],
        "captured_at": env.captured_at.isoformat() if env.captured_at else None,
        "source": env.source,
    }


# ---------------------------- bot helpers -----------------------------------


def _market_url_for_signal(signal: Signal) -> str | None:
    market = signal.market
    if not market or not market.slug:
        return None
    if market.platform and market.platform.lower() == "kalshi":
        return f"https://kalshi.com/markets/{market.slug.upper()}"
    return f"https://polymarket.com/event/{market.slug}"


def _market_url(market: Market) -> str:
    if market.platform and market.platform.lower() == "kalshi":
        return f"https://kalshi.com/markets/{market.slug.upper()}"
    return f"https://polymarket.com/event/{market.slug}"


def _extract_market_slug(market_url: str) -> str:
    parsed = urlparse(market_url.strip())
    path = parsed.path if parsed.scheme else market_url
    parts = [unquote(part).strip() for part in path.split("/") if part.strip()]
    if not parts:
        raise HTTPException(status_code=400, detail="Could not parse market URL")

    lowered = [part.lower() for part in parts]
    for marker in ("event", "markets", "market"):
        if marker in lowered:
            idx = lowered.index(marker)
            if idx + 1 < len(parts):
                return parts[idx + 1].lower()

    return parts[-1].lower()


def _event_date_for_market(market: Market | None) -> date | None:
    slug = market.slug if market else ""
    match = _SLUG_DATE_RE.search(slug)
    if not match:
        return None
    try:
        return date(int(match.group(1)), int(match.group(2)), int(match.group(3)))
    except ValueError:
        return None


def _trader_url_for_signal(signal: Signal) -> str | None:
    trader = signal.trader
    if not (trader and trader.wallet_address):
        return None
    return f"https://polymarketanalytics.com/traders/{trader.wallet_address}"


def _event_date_for_signal(signal: Signal) -> date | None:
    return _event_date_for_market(signal.market)


def _signal_bot_payload(signal: Signal, tier: str) -> dict[str, object]:
    event_date = _event_date_for_signal(signal)
    return {
        "id": signal.id,
        "tier": tier,
        "score": round(signal.score, 2),
        "confidence": round(signal.confidence, 4),
        "market": signal.market.title if signal.market else f"market#{signal.market_id}",
        "market_slug": signal.market.slug if signal.market else None,
        "market_url": _market_url_for_signal(signal),
        "event_date": event_date.isoformat() if event_date else None,
        "trader": signal.trader.nickname if signal.trader else None,
        "trader_url": _trader_url_for_signal(signal),
        "side": signal.side,
        "outcome": signal.outcome,
        "entry_price": signal.entry_price,
        "size_usd": signal.size_usd,
        "reason": signal.reason,
        "created_at": signal.created_at.isoformat() if signal.created_at else None,
    }


@router.get("/bot/status")
def bot_status(db: Session = Depends(get_db)) -> dict[str, object]:
    s = get_settings()
    falcon_health = get_falcon_health()
    recent_cutoff = datetime.utcnow() - timedelta(hours=24)
    return {
        "status": "ok",
        "environment": s.environment,
        "traders": db.scalar(select(func.count(Trader.id))) or 0,
        "markets": db.scalar(select(func.count(Market.id))) or 0,
        "signals_24h": db.scalar(select(func.count(Signal.id)).where(Signal.created_at >= recent_cutoff)) or 0,
        "discord_sent_24h": db.scalar(
            select(func.count(Alert.id)).where(
                Alert.channel == "discord",
                Alert.status == "sent",
                Alert.created_at >= recent_cutoff,
            )
        ) or 0,
        "discord_skipped_24h": db.scalar(
            select(func.count(Alert.id)).where(
                Alert.channel == "discord",
                Alert.status == "skipped",
                Alert.created_at >= recent_cutoff,
            )
        ) or 0,
        "falcon": {
            "configured": s.has_falcon_credentials(),
            "healthy": falcon_health.healthy,
            "success_rate": round(falcon_health.success_rate, 3),
            "last_scan_calls": falcon_health.last_scan_calls,
            "last_scan_successes": falcon_health.last_scan_successes,
            "last_error": falcon_health.last_error,
            "last_scan_at": (
                falcon_health.last_scan_at.isoformat()
                if falcon_health.last_scan_at
                else None
            ),
        },
        "timestamp": datetime.utcnow().isoformat(),
    }


@router.get("/bot/high-conviction")
def bot_high_conviction(
    db: Session = Depends(get_db),
    limit: int = 5,
    hours: int = 24,
    event_date_from: date | None = None,
) -> dict[str, object]:
    limit = max(1, min(limit, 10))
    hours = max(1, min(hours, 168))
    since = datetime.utcnow() - timedelta(hours=hours)
    candidates = list(
        db.scalars(
            select(Signal)
            .where(Signal.created_at >= since)
            .order_by(desc(Signal.score), desc(Signal.created_at))
            .limit(100)
        )
    )

    matches: list[dict[str, object]] = []
    near_misses: list[dict[str, object]] = []
    for signal in candidates:
        event_date = _event_date_for_signal(signal)
        if event_date_from and event_date and event_date < event_date_from:
            continue
        decision = evaluate_alert_decision(db, signal)
        if decision.tier in {"high_conviction", "possible_entry"}:
            payload = _signal_bot_payload(signal, decision.tier)
            payload.update(
                {
                    "action": decision.action,
                    "chase_risk": decision.chase_risk,
                    "total_tracked_size": round(decision.context.total_tracked_size, 2),
                    "trader_count": decision.context.trader_count,
                    "current_price": decision.context.current_price,
                    "entry_price_min": decision.context.entry_price_min,
                    "entry_price_max": decision.context.entry_price_max,
                }
            )
            matches.append(payload)
        elif len(near_misses) < 3:
            payload = _signal_bot_payload(signal, decision.tier)
            payload.update(
                {
                    "failed_reason": decision.reason,
                    "action": decision.action,
                    "chase_risk": decision.chase_risk,
                    "total_tracked_size": round(decision.context.total_tracked_size, 2),
                    "trader_count": decision.context.trader_count,
                    "current_price": decision.context.current_price,
                    "entry_price_min": decision.context.entry_price_min,
                    "entry_price_max": decision.context.entry_price_max,
                }
            )
            near_misses.append(payload)
        if len(matches) >= limit:
            break

    return {
        "count": len(matches),
        "hours": hours,
        "event_date_from": event_date_from.isoformat() if event_date_from else None,
        "discord_tiers": sorted(DISCORD_TIERS),
        "signals": matches,
        "near_misses": near_misses,
        "timestamp": datetime.utcnow().isoformat(),
    }


@router.get("/bot/search")
def bot_search_market(
    market_url: str,
    db: Session = Depends(get_db),
    limit: int = 10,
) -> dict[str, object]:
    limit = max(1, min(limit, 25))
    slug = _extract_market_slug(market_url)
    market = db.scalar(
        select(Market).where(func.lower(Market.slug) == slug.lower())
    )
    if market is None:
        raise HTTPException(
            status_code=404,
            detail=f"Market '{slug}' has not been seen by SignalForge yet",
        )

    trades = list(
        db.scalars(
            select(Trade)
            .where(Trade.market_id == market.id)
            .order_by(Trade.timestamp.desc())
        )
    )
    signals = list(
        db.scalars(
            select(Signal)
            .where(Signal.market_id == market.id)
            .order_by(desc(Signal.score), desc(Signal.confidence), desc(Signal.created_at))
        )
    )
    signals_by_key: dict[tuple[int | None, str | None, str | None], Signal] = {}
    for signal in signals:
        key = (signal.trader_id, signal.side, signal.outcome)
        signals_by_key.setdefault(key, signal)

    grouped: dict[tuple[int, str, str | None], list[Trade]] = {}
    for trade in trades:
        grouped.setdefault((trade.trader_id, trade.side, trade.outcome), []).append(trade)

    positions: list[dict[str, object]] = []
    for (trader_id, side, outcome), grouped_trades in grouped.items():
        trader = grouped_trades[0].trader
        total_size = sum(t.size_usd or 0 for t in grouped_trades)
        weighted_price_sum = sum((t.price or 0) * (t.size_usd or 0) for t in grouped_trades)
        avg_entry = weighted_price_sum / total_size if total_size > 0 else None
        first_trade = min(grouped_trades, key=lambda t: t.timestamp)
        last_trade = max(grouped_trades, key=lambda t: t.timestamp)
        signal = signals_by_key.get((trader_id, side, outcome))
        if signal is None:
            signal = signals_by_key.get((trader_id, side, None))

        score = signal.score if signal else trader.trust_score if trader else 0.0
        confidence = signal.confidence if signal else 0.0
        reason = signal.reason if signal else f"{len(grouped_trades)} trade(s) found for this market"
        trader_url = (
            f"https://polymarketanalytics.com/traders/{trader.wallet_address}"
            if trader and trader.wallet_address
            else None
        )

        positions.append(
            {
                "market": market.title,
                "market_slug": market.slug,
                "market_url": _market_url(market),
                "event_date": (
                    _event_date_for_market(market).isoformat()
                    if _event_date_for_market(market)
                    else None
                ),
                "trader": trader.nickname if trader else f"trader#{trader_id}",
                "trader_url": trader_url,
                "wallet": trader.wallet_address if trader else None,
                "side": side,
                "outcome": outcome,
                "avg_entry_price": round(avg_entry, 4) if avg_entry is not None else None,
                "total_size_usd": round(total_size, 2),
                "trade_count": len(grouped_trades),
                "first_trade_at": first_trade.timestamp.isoformat() if first_trade.timestamp else None,
                "last_trade_at": last_trade.timestamp.isoformat() if last_trade.timestamp else None,
                "score": round(score, 2),
                "confidence": round(confidence, 4),
                "reason": reason,
            }
        )

    positions.sort(
        key=lambda p: (
            float(p.get("score") or 0),
            float(p.get("confidence") or 0),
            float(p.get("total_size_usd") or 0),
        ),
        reverse=True,
    )

    return {
        "market": market.title,
        "market_slug": market.slug,
        "market_url": _market_url(market),
        "event_date": (
            _event_date_for_market(market).isoformat()
            if _event_date_for_market(market)
            else None
        ),
        "count": len(positions[:limit]),
        "positions": positions[:limit],
        "timestamp": datetime.utcnow().isoformat(),
    }


# ---------------------------- run-scan --------------------------------------


@router.post("/run-scan", response_model=ScanResult)
async def trigger_scan() -> ScanResult:
    return await run_scan_once()


# ---------------------------- falcon-test -----------------------------------

# LaBradfordSmith22 from the seeded watchlist — a known-good wallet to probe.
_DEFAULT_TEST_WALLET = "0x9495425feeb0c250accb89275c97587011b19a27"


@router.get("/falcon-test")
async def falcon_test(
    wallet: str = _DEFAULT_TEST_WALLET,
    agent_id: int = FalconProvider.AGENT_WALLET_360,
    window_days: int = 3,
) -> dict[str, object]:
    """Probe a single Falcon agent and return the raw response.

    Useful for verifying the API key works and discovering the actual response
    shape so the parser in FalconProvider can be tightened. Defaults to
    agent_id=581 (Wallet 360) against LaBradfordSmith22's wallet.
    """
    s = get_settings()
    if not s.has_falcon_credentials():
        raise HTTPException(
            status_code=400,
            detail="SIGNALFORGE_FALCON_API_KEY is not set",
        )

    falcon = FalconProvider(s.falcon_api_key, s.falcon_base_url)
    raw = await falcon.query_agent(
        agent_id,
        params={"proxy_wallet": wallet, "window_days": str(window_days)},
    )
    health = get_falcon_health()
    return {
        "agent_id": agent_id,
        "wallet": wallet,
        "window_days": window_days,
        "ok": raw is not None,
        "raw_response": raw,
        "falcon_health": {
            "last_status_code": health.last_status_code,
            "last_error": health.last_error,
            "last_endpoint": health.last_endpoint,
            "last_agent_id": health.last_agent_id,
        },
    }


# ---------------------------- dashboard -------------------------------------


@router.get("/dashboard-summary", response_model=DashboardSummary)
def dashboard_summary(db: Session = Depends(get_db)) -> DashboardSummary:
    active_signals_raw = list(
        db.scalars(
            select(Signal).order_by(desc(Signal.score), desc(Signal.created_at)).limit(10)
        )
    )
    active_signals = [_enrich_signal(s) for s in active_signals_raw]

    top_traders = list(
        db.scalars(
            select(Trader).order_by(desc(Trader.trust_score)).limit(10)
        )
    )

    # "Highest conviction" markets = those carrying the highest-scored signals.
    top_market_ids_query = (
        select(Signal.market_id, func.max(Signal.score).label("max_score"))
        .group_by(Signal.market_id)
        .order_by(desc("max_score"))
        .limit(10)
    )
    top_market_ids = [row[0] for row in db.execute(top_market_ids_query).all()]
    if top_market_ids:
        markets = list(db.scalars(select(Market).where(Market.id.in_(top_market_ids))))
        # preserve order from the score query
        order = {mid: idx for idx, mid in enumerate(top_market_ids)}
        markets.sort(key=lambda m: order.get(m.id, 999))
    else:
        markets = list(db.scalars(select(Market).limit(10)))

    recent_alerts = list(
        db.scalars(select(Alert).order_by(desc(Alert.created_at)).limit(10))
    )

    # Watchlist health: how complete is our trader enrichment?
    all_traders = list(db.scalars(select(Trader)))
    enriched = [t for t in all_traders if t.total_pnl is not None or t.trader_rank is not None]
    win_rates = [t.win_rate for t in all_traders if t.win_rate is not None]
    health = WatchlistHealth(
        total_traders=len(all_traders),
        enriched_traders=len(enriched),
        avg_trust_score=round(
            sum(t.trust_score for t in all_traders) / max(len(all_traders), 1), 2
        ),
        avg_win_rate=round(sum(win_rates) / len(win_rates), 4) if win_rates else None,
        enabled_for_copy=sum(1 for t in all_traders if t.copy_enabled),
    )

    # Simulated PnL is a placeholder — the MVP doesn't execute trades.
    simulated_pnl = 0.0

    return DashboardSummary(
        active_signals=active_signals,
        top_traders=top_traders,
        highest_conviction_markets=markets,
        recent_alerts=recent_alerts,
        simulated_pnl_usd=simulated_pnl,
        watchlist_health=health,
    )
