from __future__ import annotations

from datetime import datetime

import pytest
from fastapi import HTTPException

from app.api.routes import (
    baseball_pitcher_statcast_summary,
    baseball_statcast_cache_status,
    baseball_pitcher_statcast,
)
from app.config import get_settings
from app.models import PitcherStatcastSummary


@pytest.mark.asyncio
async def test_live_statcast_is_disabled_by_default(monkeypatch):
    monkeypatch.setenv("SIGNALFORGE_ALLOW_LIVE_PYBASEBALL_REQUESTS", "false")
    get_settings.cache_clear()

    with pytest.raises(HTTPException) as exc:
        await baseball_pitcher_statcast(592789, "2026-05-01", "2026-05-01")

    assert exc.value.status_code == 409
    assert exc.value.detail == (
        "Live pybaseball requests disabled. Use cached Statcast summaries generated by worker."
    )
    get_settings.cache_clear()


def test_cached_pitcher_summary_reads_from_db(db_session):
    summary = PitcherStatcastSummary(
        player_id=592789,
        player_name="Sample Pitcher",
        season=2026,
        last_n_days=14,
        games=2,
        innings_pitched=11.2,
        strikeouts=14,
        walks=3,
        pitch_count_avg=91.5,
        strikeouts_per_start=7.0,
        whiff_rate=0.31,
        chase_rate=0.28,
        k_rate=0.32,
        updated_at=datetime(2026, 5, 25, 12, 0, 0),
        source="pybaseball_worker",
    )
    db_session.add(summary)
    db_session.commit()

    payload = baseball_pitcher_statcast_summary(592789, db=db_session)

    assert payload["player_name"] == "Sample Pitcher"
    assert payload["strikeouts_per_start"] == 7.0
    assert payload["source"] == "pybaseball_worker"


def test_statcast_cache_status_reads_counts(db_session):
    db_session.add(
        PitcherStatcastSummary(
            player_id=1,
            player_name="A",
            season=2026,
            last_n_days=14,
            updated_at=datetime(2026, 5, 25, 12, 0, 0),
        )
    )
    db_session.commit()

    payload = baseball_statcast_cache_status(db=db_session)

    assert payload["pitcher_summaries"] == 1
